### ISSUE TITLE
Javascript Validation

### ISSUE THREAD

**Issue by evanlws12** [evanlws12/423-Term-Project#17]

**Comment by evanlws12** [comment]
He said stuff like:
Dollar vs. Percent - let user type in percent then divide by 100
Watch for special characters

**Comment by evanlws12** [comment]
Periods, Commas, Hashtags and The equal symbol is allowed in the database

**Comment by mslomski** [comment]
I will work on this.

**Comment by evanlws12** [comment]
@mslomski Ok well if you're working on insert ad event validation, I did add a date picker but they can still enter a string. TECHNICALLY if we just use the picker every time it does not have to be validated but if they type in a date manually then it needs to me in this format: MM/DD/YYYY. This way it is readable, and I format it before adding it to the database in PHP.

**Comment by rconn4** [comment]
@mslomski @evanlws12  If your still going with the validation, my 2 search functions and the 2 reports we just added that will be merged with master soon.  With the field validations we also need to make sure at least one of the radio buttons is checked as well as one of the check boxes is checked.

**Comment by rconn4** [comment]
@mslomski @evanlws12 Do we have any validation for ad event?

**Comment by evanlws12** [comment]
Still need validation for updates

**Comment by mslomski** [comment]
I will continue to work on this for the updates and the datepicker validation.

**Comment by lblow1** [comment]
On the page insert_ad_event_view.html the validation says that the event code is wrong, but it still goes to the next page

**Comment by evanlws12** [comment]
I'll look at it

**Comment by evanlws12** [comment]
Ok the description validation is still messing stuff up so for the time being I removed it. The ad event view works now because the entire page was crashing on description so it just kept going

**Comment by mslomski** [comment]
Since Evan made the datepicker he can make the validation for the dates work.

**Comment by evanlws12** [comment]
Is the only file with date validation, validate_ad_event.js? If so, it's done

**Comment by mslomski** [comment]
That is the only one that I made that is needing date validation. Are we having the date picker validation apply for updating an ad event? If so, then we should add that.

**Comment by evanlws12** [comment]
Well were we adding validation for updates? I kinda thought that's what you were working on next. If so then yeah it'll work for that too. It's really all the same code. If you add validation for updating stuff then just take the code from insert

**Comment by rconn4** [comment]
Ive already done the code for the validation for updates.  But notice the new issue #94 that the validation is failing now with the description field.  Also, We need to fix the amount off for promotions since that is broken as well. @mslomski @evanlws12

**Comment by evanlws12** [comment]
The amount off for promotions? I don't remember the details about that but I can take a look at that and @mslomski can fix the validation if that's alright with him

**Comment by rconn4** [comment]
@evanlws12 The amount off validation is saying that the input is wrong no matter what the user inputs so the user is unable to ever move past that screen

**Comment by evanlws12** [comment]
For which page? insert promotion?

**Comment by mslomski** [comment]
I will take a look at this and let you know how it goes when we meet tomorrow at drake.

**Comment by mslomski** [comment]
I completed the validation for the promotion insert. This should be all that is left to do for validation.
