### ISSUE TITLE
User interface needs some work

### ISSUE THREAD

**Issue by evanlws12** [evanlws12/423-Term-Project#18]

**Comment by evanlws12** [comment]
Putting this here a reminder to put the items in the menu into a table, so they aren't scattered

**Comment by evanlws12** [comment]
Index page needs to be fixed and drop downs need to be fixed too

**Comment by evanlws12** [comment]
Messages and button names should be fixed

**Comment by evanlws12** [comment]
Tables should have table headers instead of uppercase td's

**Comment by rconn4** [comment]
@evanlws12 We could use a background color instead of plain white.

**Comment by evanlws12** [comment]
For search pages, "at least one field is required" messages
