### ISSUE TITLE
Fix back buttons in forms

### ISSUE THREAD

**Issue by evanlws12** [evanlws12/423-Term-Project#25]

**Comment by slins1** [comment]
I'll take a look at this but it won't be my first priority

**Comment by slins1** [comment]
Hey @evanlws12, I found a function to create a back button. Should I put it in the generic _script.js file that all the pages use? I know you wrote that so I figured I'd clear it by you.

Also, which pages do you think need back buttons? I can add the buttons themselves if necessary.

**Comment by evanlws12** [comment]
Yeah absolutely! We can keep generic stuff in there until there's a clear need to split up our js; I don't see that happening for a small scale project so most js should go in the _script.js

**Comment by slins1** [comment]
I have placed back buttons where I thought they were appropriate based on what we discussed. I'll leave this open for you @evanlws12 in case you see any spots I've missed where a back button should be. If not, feel free to close this issue.
