### ISSUE TITLE
Fix inconsistent HTML form implementation

### ISSUE THREAD

**Issue by mslomski** [evanlws12/423-Term-Project#32]
I noticed several inconsistencies in the design of the HTML forms. I found that it insert item they do not have the ':' symbol after every label like the other insert forms do.

I also noticed that insert promotion has inline styles for the table of the form which is not present in the insert item form table.

Someone should take a look at the HTML and improve consistency between the designs and implementations of the various forms we use.

**Comment by evanlws12** [comment]
Yeah I was pretty rough on editing these pages so the entire design is definitely half done, but imma take a look at things today and/or tomorrow for sure

**Comment by mslomski** [comment]
Also, I would prefer that we remove the use of the deprecated 'center' tag when we are creating the layout of the major HTML. If you can replace that with something more functional in CSS that would be great.

**Comment by evanlws12** [comment]
Yeah the reason I used center was It was super quick to implement (centering a div in CSS is cruel) so the fastest thing was center. I am planning to change it, I was just lazy
