### ISSUE TITLE
Description fields should allow special characters like percent

### ISSUE THREAD

**Issue by evanlws12** [evanlws12/423-Term-Project#69]

**Comment by mslomski** [comment]
Evan, you can work on this by making the % help determine what the description for the insert ad event. We have to also make sure we can modify the eventType field and the corresponding PHP after the form is submitted to make sure that it works.

**Comment by evanlws12** [comment]
I'm not sure if we really need to even validate the description field for ad event and promotion. I even think it could be optional wether the user inputs anything in it or not

**Comment by mslomski** [comment]
We should confirm this with Dr.Mitra maybe in class. I can see us not using validation, but I want to be sure so we don't get credit off for not having it.
