### ISSUE TITLE
For Item pages, the Category and Department fields must match

### ISSUE THREAD

**Issue by slins1** [evanlws12/423-Term-Project#83]
Only certain departments are part of certain categories (ex. Accessories/Footwear only has two valid departments, Accessories and Footwear).

Check the Item Master spreadsheet to see how the categories match up.

**Comment by mslomski** [comment]
Working on this.

**Comment by mslomski** [comment]
I added the functionality to have the dropdowns automatically populate with the correct corresponding data from the department dropdown compared to the category one.
